<?php
/**
 * SortByMetric
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Synerise\ItemsSearchApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Synerise search API
 *
 * Synerise search API v2.0 documentation
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Synerise\ItemsSearchApiClient\Model;
use \Synerise\ItemsSearchApiClient\ObjectSerializer;

/**
 * SortByMetric Class Doc Comment
 *
 * @category Class
 * @description Name of the metric by which the data will be sorted
 * @package  Synerise\ItemsSearchApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SortByMetric
{
    /**
     * Possible values of this enum
     */
    public const TRANSACTIONS_POPULARITY = 'TransactionsPopularity';

    public const PAGE_VISITS_POPULARITY = 'PageVisitsPopularity';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TRANSACTIONS_POPULARITY,
            self::PAGE_VISITS_POPULARITY
        ];
    }
}


