<?php /** @var $this Synerise\Integration\Block\Adminhtml\Form\Field\BusinessProfiles */ ?>
<div class="admin__control-table-wrapper">
    <table class="admin__control-table" id="synerise_business_profile_business_profile_map">
        <thead>
        <tr>
            <th><?php echo __('Website') ?></th>
            <th><?php echo __('Business Profile') ?></th>
        </tr>
        </thead>
        <tbody>
            <?php foreach($this->getRows() as $row): ?>
            <tr id="<?php echo $row['id']; ?>">
                <td class="value"><?php echo $row['name']; ?></td>
                <td>
                    <select id="synerise_business_profile_id" name="groups[business_profile][fields][map][value][<?php echo $row['id']; ?>]" class=" select admin__control-select">
                        <option value="" style="display:block"></option>
                    <?php foreach($this->getBusinessProfiles() as $businessProfile): ?>
                        <?php $isSelected = ($row['value'] == $businessProfile->getId()); ?>
                        <option value="<?php echo $businessProfile->getId(); ?>" <?php if($isSelected): ?> selected="selected"<?php endif;?>><?php echo $businessProfile->getName(); ?></option>
                    <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

