<?php
// phpcs:ignoreFile
/** @var $block Synerise\Integration\Block\Opengraph\Additional */
?>
    <meta property="product:original_price:amount" content="<?= $block->getOriginalPriceAmount(); ?>"/>
    <?= $block->getChildHtml('meta.currency') ?>
    <meta property="product:retailer_part_no" content="<?= $block->getSku(); ?>"/>
<?php foreach ($block->getFormattedCategories() as $category): ?>
    <meta property="product:category" content="<?= $category; ?>"/>
<?php endforeach;
