<?php
/** @var $block \Magento\Catalog\Block\Product\View */

/** @var $catalogHelper \Synerise\Integration\Helper\Tracking */
$catalogHelper = $this->helper(\Synerise\Integration\Helper\Catalog::class);

/** @var $trackingHelper \Synerise\Integration\Helper\Tracking */
$trackingHelper = $this->helper(\Synerise\Integration\Helper\Tracking::class);

if ($trackingHelper->isPageTrackingEnabled() && $trackingHelper->isOpengraphEnabled() && $product = $block->getProduct()):
    if ($priceAmount = $block->getProduct()
        ->getPriceInfo()
        ->getPrice(\Magento\Catalog\Pricing\Price\RegularPrice::PRICE_CODE)
        ->getAmount()):?>
        <meta property="product:original_price:amount" content="<?= $block->escapeHtmlAttr($priceAmount) ?>"/>
        <?= $block->getChildHtml('meta.currency') ?>
<meta property="product:retailer_part_no" content="<?php echo $product->getSku(); ?>"/>
        <?php
    endif;

    $categoryIds = $product->getCategoryIds();
    if ($categoryIds):
        foreach ($categoryIds as $categoryId):
            ?>
<meta property="product:category" content="<?php echo $catalogHelper->getFormattedCategoryPath($categoryId); ?>"/>
            <?php
        endforeach;
    endif;
endif;
?>