<?php /** @var $this Synerise\Integration\Block\Adminhtml\Dashboard\Status */ ?>
<div class="col-m-4">
    <div class="status-box">
        <h3><?php echo __($this->getHeader()); ?></h3>
        <p><?php echo __($this->getSubHeader()); ?></p>
        <div class="col-m-12">
            <div class="col-m-6">
                <a href="<?php echo $this->getScheduleAllUrl(); ?>"><?php echo __('Schedule synchronization'); ?></a>
            </div>
            <div class="col-m-6 status-box-items">
                <?php echo $this->getProcessedItemsCount(); ?>/<?php echo $this->getTotalItemsCount(); ?>
            </div>
        </div>
    </div>
</div>

